/*

 BACKGROUND.C

 Map Source File.

 Info:
   Section       : 
   Bank          : 0
   Map size      : 40 x 18
   Tile set      : C:\Users\MAMU\Documents\dise�oGB\simple_background.gbr
   Plane count   : 1 plane (8 bits)
   Plane order   : Tiles are continues
   Tile offset   : 0
   Split data    : No

 This file was generated by GBMB v1.8

*/

#define backgroundmapWidth 40
#define backgroundmapHeight 18
#define backgroundmapBank 0

unsigned char windowmap[] =
{
  0x12,0x0F,0x16,0x16,0x19
};

/* End of window.C */
